enabled_repos:
- rhel-server-ose-rpms
- rhel-server-ose-rpms-shipped
from:
  stream: rhel
labels:
  License: GPLv2+
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift3/prometheus
owners: []
